// <auto-generated />
using System;
using Ggio.BikeSherpa.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ggio.BikeSherpa.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.CourierAggregate.Courier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultDeliveryType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.City", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryZoneName")
                        .HasColumnType("character varying(100)");

                    b.HasKey("Name");

                    b.HasIndex("DeliveryZoneName");

                    b.ToTable("DeliveryZoneCities", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Grenoble",
                            DeliveryZoneName = "Centre"
                        },
                        new
                        {
                            Name = "Échirolles",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Eybens",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Fontaine",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "La Tronche",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Poisat",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Saint-Martin-d’Hères",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Saint-Martin-le-Vinoux",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Seyssinet-Pariset",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Seyssins",
                            DeliveryZoneName = "Limitrophe"
                        },
                        new
                        {
                            Name = "Sassenage",
                            DeliveryZoneName = "Périphérie"
                        },
                        new
                        {
                            Name = "Saint-Égrève",
                            DeliveryZoneName = "Périphérie"
                        },
                        new
                        {
                            Name = "Meylan",
                            DeliveryZoneName = "Périphérie"
                        },
                        new
                        {
                            Name = "Gières",
                            DeliveryZoneName = "Périphérie"
                        },
                        new
                        {
                            Name = "Bresson",
                            DeliveryZoneName = "Périphérie"
                        },
                        new
                        {
                            Name = "Le Pont-de-Claix",
                            DeliveryZoneName = "Périphérie"
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.Delay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Delays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "StandardCost",
                            Label = "Jour même",
                            Price = 0.0
                        },
                        new
                        {
                            Id = "LastMinuteOrderExtraCost",
                            Label = "Prioritaire",
                            Price = 3.0
                        },
                        new
                        {
                            Id = "EarlyOrderDiscount",
                            Label = "",
                            Price = -2.0
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ContractDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Details")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double?>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("DiscountReason")
                        .HasColumnType("text");

                    b.Property<double?>("ExtraCost")
                        .HasColumnType("double precision");

                    b.Property<string>("ExtraCostReason")
                        .HasColumnType("text");

                    b.Property<bool>("InsulatedBox")
                        .HasColumnType("boolean");

                    b.Property<bool>("NeedEstimate")
                        .HasColumnType("boolean");

                    b.Property<int>("PricingStrategy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencyName")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UrgencyName");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.DeliveryZone", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("SimplePrice")
                        .HasColumnType("double precision");

                    b.Property<double>("TourPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Name");

                    b.ToTable("DeliveryZones", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Centre",
                            SimplePrice = 1.0,
                            TourPrice = 5.0
                        },
                        new
                        {
                            Name = "Limitrophe",
                            SimplePrice = 2.5,
                            TourPrice = 8.0
                        },
                        new
                        {
                            Name = "Périphérie",
                            SimplePrice = 5.5,
                            TourPrice = 0.0
                        },
                        new
                        {
                            Name = "Extérieur",
                            SimplePrice = 11.0,
                            TourPrice = 0.0
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.PackingSize", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double>("SimplePrice")
                        .HasColumnType("double precision");

                    b.Property<double>("TourPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Name");

                    b.ToTable("PackingSizes", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "S",
                            Label = "S = jusqu'à 3kg / 45cm",
                            Order = 1,
                            SimplePrice = 3.0,
                            TourPrice = 0.0
                        },
                        new
                        {
                            Name = "M",
                            Label = "M = jusqu'à 10kg / 100cm",
                            Order = 2,
                            SimplePrice = 5.0,
                            TourPrice = 2.0
                        },
                        new
                        {
                            Name = "L",
                            Label = "L = jusqu'à 20kg / 120cm",
                            Order = 3,
                            SimplePrice = 7.0,
                            TourPrice = 4.0
                        },
                        new
                        {
                            Name = "XL",
                            Label = "XL = jusqu'à 30kg / 120cm",
                            Order = 4,
                            SimplePrice = 9.0,
                            TourPrice = 6.0
                        },
                        new
                        {
                            Name = "XXL",
                            Label = "XXL = jusqu'à 40kg (sur devis)",
                            Order = 5,
                            SimplePrice = 11.0,
                            TourPrice = 8.0
                        },
                        new
                        {
                            Name = "XXXL",
                            Label = "XXXL = jusqu'à 50kg (sur devis)",
                            Order = 6,
                            SimplePrice = 13.0,
                            TourPrice = 10.0
                        },
                        new
                        {
                            Name = "XXXXL",
                            Label = "XXXXL = jusqu'à 60kg (sur devis)",
                            Order = 7,
                            SimplePrice = 15.0,
                            TourPrice = 12.0
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.Urgency", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan?>("AddTimeLimit")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("FixedTimeLimit")
                        .HasColumnType("interval");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastHourToOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double>("PriceCoefficient")
                        .HasColumnType("double precision");

                    b.HasKey("Name");

                    b.ToTable("Urgencies", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Eco",
                            FixedTimeLimit = new TimeSpan(0, 17, 0, 0, 0),
                            Label = "Avant 17h le jour-même (Eco)",
                            LastHourToOrder = 12,
                            Order = 1,
                            PriceCoefficient = 0.75
                        },
                        new
                        {
                            Name = "Standard",
                            AddTimeLimit = new TimeSpan(0, 2, 30, 0, 0),
                            Label = "2h30 (Standard)",
                            LastHourToOrder = 15,
                            Order = 2,
                            PriceCoefficient = 1.25
                        },
                        new
                        {
                            Name = "Urgent",
                            AddTimeLimit = new TimeSpan(0, 1, 0, 0, 0),
                            Label = "1h (Urgent)",
                            LastHourToOrder = 20,
                            Order = 3,
                            PriceCoefficient = 2.0
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Infrastructure.Repositories.Parameter", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Parameters", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "VAT_RATE",
                            Value = "20"
                        },
                        new
                        {
                            Key = "LAST_HOUR_TO_ORDER",
                            Value = "15"
                        },
                        new
                        {
                            Key = "WORK_START_DATE",
                            Value = "0001-01-01T08:00:00"
                        },
                        new
                        {
                            Key = "WORK_END_DATE",
                            Value = "0001-01-01T19:00:00"
                        },
                        new
                        {
                            Key = "SIMPLE_DELIVERY_MAIL_TEMPLATE",
                            Value = "Your delivery is ready for pickup at {pickupLocation} on {pickupDate}. {deliverycode} { pickupaddress} { destinationaddress} {PickupDate} {LoadingSlot} "
                        },
                        new
                        {
                            Key = "SIMPLE_DELIVERY_MAIL_SUBJECT",
                            Value = "Delivery Ready for Pickup"
                        },
                        new
                        {
                            Key = "TOUR_DELIVERY_MAIL_TEMPLATE",
                            Value = "Your delivery is ready for pickup at {pickupLocation} on {pickupDate}. {deliverycode} { pickupaddress} { destinationaddress} {PickupDate} {LoadingSlot} "
                        },
                        new
                        {
                            Key = "TOUR_DELIVERY_MAIL_SUBJECT",
                            Value = "Tour delivery Ready for Pickup"
                        },
                        new
                        {
                            Key = "EARLY_ORDER_LIMIT_IN_HOURS",
                            Value = "18"
                        },
                        new
                        {
                            Key = "LAST_MINUTE_ORDER_LIMIT_IN_HOURS",
                            Value = "2"
                        });
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.CourierAggregate.Courier", b =>
                {
                    b.OwnsOne("Ggio.BikeSherpa.Backend.Domain.SharedKernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CourierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Complement")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Coordinates")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("StreetInfo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("CourierId");

                            b1.ToTable("Couriers");

                            b1.WithOwner()
                                .HasForeignKey("CourierId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.CustomerAggregate.Customer", b =>
                {
                    b.OwnsOne("Ggio.BikeSherpa.Backend.Domain.SharedKernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Complement")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Coordinates")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("StreetInfo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.City", b =>
                {
                    b.HasOne("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.DeliveryZone", null)
                        .WithMany("Cities")
                        .HasForeignKey("DeliveryZoneName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.Delivery", b =>
                {
                    b.HasOne("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.Urgency", "Urgency")
                        .WithMany()
                        .HasForeignKey("UrgencyName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.DeliveryStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string[]>("AttachmentFilePaths")
                                .HasColumnType("text[]");

                            b1.Property<string>("Comment")
                                .HasColumnType("text");

                            b1.Property<bool>("Completed")
                                .HasColumnType("boolean");

                            b1.Property<string>("CourierComment")
                                .HasColumnType("text");

                            b1.Property<Guid?>("CourierId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision");

                            b1.Property<DateTimeOffset>("EstimatedDeliveryDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("NotBilled")
                                .HasColumnType("boolean");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("PackingSizeName")
                                .IsRequired()
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset?>("RealDeliveryDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("StepType")
                                .HasColumnType("integer");

                            b1.Property<string>("StepZoneName")
                                .IsRequired()
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("DeliveryId");

                            b1.HasIndex("PackingSizeName");

                            b1.HasIndex("StepZoneName");

                            b1.ToTable("DeliverySteps", (string)null);

                            b1.WithOwner("ParentDelivery")
                                .HasForeignKey("DeliveryId");

                            b1.HasOne("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.PackingSize", "PackingSize")
                                .WithMany()
                                .HasForeignKey("PackingSizeName")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.DeliveryZone", "StepZone")
                                .WithMany()
                                .HasForeignKey("StepZoneName")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("Ggio.BikeSherpa.Backend.Domain.SharedKernel.Address", "StepAddress", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryStepId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Complement")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<string>("Coordinates")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<string>("Phone")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasMaxLength(5)
                                        .HasColumnType("character varying(5)");

                                    b2.Property<string>("StreetInfo")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.HasKey("DeliveryStepId");

                                    b2.ToTable("DeliverySteps");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryStepId");
                                });

                            b1.Navigation("PackingSize");

                            b1.Navigation("ParentDelivery");

                            b1.Navigation("StepAddress")
                                .IsRequired();

                            b1.Navigation("StepZone");
                        });

                    b.Navigation("Steps");

                    b.Navigation("Urgency");
                });

            modelBuilder.Entity("Ggio.BikeSherpa.Backend.Domain.DeliveryAggregate.DeliveryZone", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
