// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Ggio.BikeSherpa.Backend.Infrastructure.GeoService.Contracts;

#nullable enable annotations

namespace Ggio.BikeSherpa.Backend.Infrastructure.GeoService
{
    /// <summary>Service d'itinéraire et d'isochrone</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IItineraryApi
    {
        /// <summary>Calculer un itinéraire</summary>
        /// <remarks>Calculer un itinéraire en fournissant un point de départ et un point d'arrivé. Plusieurs options peuvent être fournies.</remarks>
        /// <param name="resource">Ressource utilisée pour le calcul. Les valeurs disponibles sont présentes dans le GetCapabilities. Une ressource est un graphe de navigation qui peut potentiellement avoir plusieurs modes de transports et de calculs. La ressource va plutôt parler du graphe, de la topologie de la donnée. Par exemple, il pourra s'agir d'un graphe de navigation issu de la BDTOPO v3 permettant de trouver l'itinéraire le plus court pour une voiture.</param>
        /// <param name="start">Point de départ. Il devra être exprimé dans le CRS, par défaut, de la ressource (voir le paramètre 'crs' dans le GetCapabilities).</param>
        /// <param name="end">Point d'arrivée. Il devra être exprimé dans le CRS, par défaut, de la ressource (voir le paramètre 'crs' dans le GetCapabilities).</param>
        /// <param name="intermediates">Points intermédiaires. Ils devront être exprimés dans le CRS, par défaut, de la ressource (voir le paramètre 'crs' dans le GetCapabilities).</param>
        /// <param name="profile">Mode de déplacement utilisé pour le calcul. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="optimization">Mode de calcul utilisé pour déterminer l'itinéraire. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="geometryFormat">Format des géométries dans la réponse. Peuvent être au format GeoJSON ou Encoded Polyline.</param>
        /// <param name="constraints">Contraintes utilisées pour le calcul. Il s'agit d'un objet JSON (voir la version POST de cette opération). Les paramètres disponibles sont présents dans le GetCapabilities.</param>
        /// <param name="getSteps">Présence des étapes dans la réponse. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="getBbox">Présence de l'emprise de l'itinéraire dans la réponse. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="distanceUnit">Unité des distances renvoyées. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="timeUnit">Unité du temps renvoyé. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="crs">Projection des géometries. Les valeurs disponibles et la valeur par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="waysAttributes">Attributs des tronçons à afficher dans la réponse. Les valeurs disponibles et les valeurs par défaut utilisées sont présentes dans le GetCapabilities.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>successful operation</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Invalid parameters</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Not allowed</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/itineraire")]
        Task<Itineraire> RouteItineraireGet([Query] string resource, [Query] string start, [Query] string end, [Query(CollectionFormat.Multi)] IEnumerable<string> intermediates, [Query] string profile, [Query] string optimization, [Query] GeometryFormat? geometryFormat, [Query(CollectionFormat.Multi)] IEnumerable<string> constraints, [Query] bool? getSteps, [Query] bool? getBbox, [Query] string distanceUnit, [Query] string timeUnit, [Query] string crs, [Query(CollectionFormat.Multi)] IEnumerable<string> waysAttributes, CancellationToken cancellationToken = default);

        /// <summary>Calculer un itinéraire</summary>
        /// <remarks>Calculer un itinéraire en fournissant un point de départ et un point d'arrivé. Plusieurs options peuvent être fournies.</remarks>
        /// <param name="body">body parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>successful operation</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Invalid parameters</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Not allowed</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not found</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/itineraire")]
        Task<Itineraire> RouteItinerairePost([Body] RouteBody body, CancellationToken cancellationToken = default);


    }

}